// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAllRefreshTokens(ctx context.Context, userID pgtype.UUID) error
	DeleteRefreshToken(ctx context.Context, tokenHash string) error
	EmailExists(ctx context.Context, email string) (bool, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	IncrementFailedAttempts(ctx context.Context, id pgtype.UUID) error
	SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) error
	UpdateLoginSuccess(ctx context.Context, id pgtype.UUID) error
	UsernameExists(ctx context.Context, username string) (bool, error)
}

var _ Querier = (*Queries)(nil)
