import { Server } from "./types";

export const servers: Server[] = [
  {
    id: 1,
    rank: 1,
    name: "AlwiNation",
    slug: "alwination",
    banner:
      "https://minecraft-mp.com/images/banners/banner-339723-1739705570.mp4",
    bannerType: "video",
    logo: "https://minecraft-mp.com/images/favicon/339723.png?ts=1780804305",
    ip: "alwination.id",
    players: { online: 887, max: 1888 },
    votes: "26.2K",
    ping: 12,
    description:
      "Server Minecraft Indonesia dengan konsep casual dan cross-play. Tersedia Earth, Skyblock, SMP Survival dan Vanilla.",
    tags: ["Survival", "Skyblock", "Earth", "SMP", "Vanilla", "Cross-Play"],
    version: "1.20 - 26.2",
    shorts: [
      {
        title: "Server Tour 2026!",
        url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        thumbnail: "https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg",
        views: "12.4K",
        serverName: "AlwiNation",
      },
      {
        title: "Skyblock Challenge EP.1",
        url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        thumbnail: "https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg",
        views: "8.2K",
        serverName: "AlwiNation",
      },
    ],
  },
  {
    id: 2,
    rank: 2,
    name: "relxmc",
    slug: "relxmc",
    banner:
      "https://minecraft-mp.com/images/banners/banner-353709-1769624693.mp4",
    bannerType: "video",
    logo: "https://minecraft-mp.com/images/favicon/353709.png?ts=1783400479",
    ip: "relxmc.com",
    players: { online: 144, max: 1000 },
    votes: "18.5K",
    ping: 23,
    description:
      "Server dengan fitur Cross-Play, Economy, PvP, Ranks dan Survival. Bergabung dengan komunitas yang aktif!",
    tags: ["Survival", "Economy", "PvP", "Ranks", "Cross-Play"],
    version: "1.20 - 26.2",
    shorts: [
      {
        title: "PvP Tournament Highlight",
        url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        thumbnail: "https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg",
        views: "5.1K",
        serverName: "relxmc",
      },
    ],
  },
  {
    id: 3,
    rank: 3,
    name: "KandangAlwi",
    slug: "kandangalwi",
    banner:
      "https://minecraft-mp.com/images/banners/banner-287720-1738749575.mp4",
    bannerType: "video",
    logo: "https://minecraft-mp.com/images/favicon/287720.png?ts=1780936541",
    ip: "kalwi.id",
    players: { online: 180, max: 2026 },
    votes: "15.8K",
    ping: null,
    description:
      "Server dengan fitur lengkap: Cross-Play, Discord, Economy, Jobs, Land Claim, OneBlock, Ranks, Skyblock dan Survival.",
    tags: [
      "Survival",
      "Skyblock",
      "OneBlock",
      "Economy",
      "Jobs",
      "Land Claim",
      "Ranks",
      "Cross-Play",
      "Discord",
    ],
    version: "1.20 - 26.1.2",
    shorts: [
      {
        title: "OneBlock Progression",
        url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        thumbnail: "https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg",
        views: "3.7K",
        serverName: "KandangAlwi",
      },
    ],
  },
  {
    id: 4,
    rank: 4,
    name: "Kaizen Network",
    slug: "kaizen-network",
    banner:
      "https://minecraft-mp.com/images/banners/banner-306253-1776240611.mp4",
    bannerType: "video",
    logo: "https://minecraft-mp.com/images/favicon/306253.png?ts=1781362886",
    ip: "mp.kaizenmc.id",
    players: { online: 81, max: 6767 },
    votes: "12.4K",
    ping: null,
    description:
      "Server Minecraft Indonesia yang menghadirkan pengalaman bermain terbaik untuk semua pemain dengan berbagai game mode.",
    tags: [
      "Survival",
      "Skyblock",
      "Creative",
      "Roleplay",
      "Economy",
      "Land Claim",
      "PvP",
      "Cross-Play",
      "Discord",
    ],
    version: "1.20 - 26.2",
    shorts: [
      {
        title: "Kaizen Server Spotlight",
        url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        thumbnail: "https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg",
        views: "6.8K",
        serverName: "Kaizen Network",
      },
    ],
  },
  {
    id: 5,
    rank: 5,
    name: "Minesive",
    slug: "minesive",
    banner:
      "https://minecraft-mp.com/images/banners/banner-333355-1721379218.mp4",
    bannerType: "video",
    logo: "https://minecraft-mp.com/images/favicon/333355.png?ts=1780886441",
    ip: "minesive.com",
    players: { online: 502, max: 1000 },
    votes: "8.5K",
    ping: null,
    description:
      "Server Minecraft dengan era baru. Tersedia Economy, Events, Manhunt, OneBlock, Practice, PvP, dan Survival seru!",
    tags: [
      "Survival",
      "Economy",
      "Events",
      "PvP",
      "SMP",
      "War",
      "OneBlock",
      "Manhunt",
      "Practice",
      "Cross-Play",
    ],
    version: "1.20 - 26.2",
    shorts: [
      {
        title: "Minesive New Era Trailer",
        url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        thumbnail: "https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg",
        views: "2.1K",
        serverName: "Minesive",
      },
    ],
  },
  {
    id: 6,
    rank: 6,
    name: "Potato SMP",
    slug: "potato-smp",
    banner: "",
    bannerType: "image",
    logo: "https://minecraft-mp.com/images/favicon/353692.png?ts=1782563625",
    ip: "play.potatosmp.my.id:19132",
    players: { online: 50, max: 200 },
    votes: "1.3K",
    ping: null,
    description:
      "Server Minecraft bertema survival economy dengan gamemode PvP, mining sim, area AFK, dan farming. Cocok untuk semua pemain!",
    tags: [
      "Survival",
      "Economy",
      "PvP",
      "SMP",
      "Adventure",
      "Land Claim",
      "Minigames",
      "Ranks",
      "Cross-Play",
    ],
    version: "1.21.11",
    shorts: [
      {
        title: "Farming Guide Potato SMP",
        url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        thumbnail: "https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg",
        views: "1.2K",
        serverName: "Potato SMP",
      },
    ],
  },
  {
    id: 7,
    rank: 7,
    name: "MineGens",
    slug: "minegens",
    banner:
      "https://minecraft-mp.com/images/banners/banner-320411-1686920875.mp4",
    bannerType: "video",
    logo: "https://minecraft-mp.com/images/favicon/320411.png?ts=1777281983",
    ip: "minegens.id",
    players: { online: 113, max: 125 },
    votes: "5.2K",
    ping: null,
    description:
      "First Gens Tycoon server di Indonesia. Nikmati Skyblock, OneBlock, Survival, dan fitur lengkap dengan komunitas aktif!",
    tags: [
      "Survival",
      "Skyblock",
      "OneBlock",
      "Economy",
      "Ranks",
      "Jobs",
      "Land Claim",
      "Cross-Play",
      "Discord",
      "Vanilla",
    ],
    version: "1.20 - 26.1.2",
    shorts: [
      {
        title: "Skyblock Tips & Tricks",
        url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        thumbnail: "https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg",
        views: "4.5K",
        serverName: "MineGens",
      },
    ],
  },
];
